.github/workflows/main.yml, .mkdocs/.gitignore, .mkdocs/mkdocs.yml, .mkdocs/requirements.txt, Makefile
mkdocs provides a nice searchable interface for the markdown docs.
=> docs: render mkdocs site on github pages

Makefile, grafonnet-base/main.libsonnet, grafonnet-base/util/main.libsonnet, grafonnet-base/util/panel.libsonnet, grafonnet-base/veneer/dashboard.libsonnet, grafonnet-base/veneer/main.libsonnet, test/jsonnetfile.json, test/util_test.jsonnet
This PR adds a framework to write jsonnet unit tests in `test/` and adds a make target `make test` to run the tests.
This PR also incldues small refactor on `grafonnet-base/` a bit to facilitate for easier unit testing.
=> feat: add initial framework for unit tests

docs/grafonnet/util.md, gen/grafonnet-v9.4.0/docs/grafonnet/util.md, grafonnet-base/util/dashboard.libsonnet, grafonnet-base/util/main.libsonnet, grafonnet-base/veneer/dashboard.libsonnet, test/util_test.jsonnet
=> fix(base): set options/current for custom template variables

docs/README.md, docs/grafonnet/query/loki.md, docs/grafonnet/query/tempo.md, gen/grafonnet-v9.4.0/docs/grafonnet/query/loki.md, gen/grafonnet-v9.4.0/docs/grafonnet/query/tempo.md, grafonnet-base/veneer/main.libsonnet, grafonnet-base/veneer/query.libsonnet
This PR also renders the docs again, adding a few pieces we missed from previous PRs.
=> feat(veneer): add constructor for loki/tempo

grafonnet-base/jsonnetfile.json, grafonnet-base/main.libsonnet
We've moved CRDsonnet to its own org.
=> fix(base): move crdsonnet to org

grafonnet-base/util/dashboard.libsonnet, test/util_test.jsonnet
ref: #28
Comment: https://github.com/grafana/grafonnet/issues/28#issuecomment-1518182132
=> feat(veneer): take escaped comma into consideration for Custom queries

docs/grafonnet/query/azureMonitor.md, docs/grafonnet/query/cloudWatch.md, gen/grafonnet-v9.4.0/docs/grafonnet/query/azureMonitor.md, gen/grafonnet-v9.4.0/docs/grafonnet/query/cloudWatch.md, grafonnet-base/main.libsonnet
related: https://github.com/grafana/grafonnet/issues/38
=> fix(base): ensure that code/docs for CloudWatch/AzureMonitor gets rendered

examples/redMethod/lib/redDashboard/main.libsonnet, examples/redMethod/lib/redDashboard/queries/prometheus.libsonnet, examples/redMethod/lib/redDashboard/queries/testdata.libsonnet, examples/redMethod/main.libsonnet, examples/runtimeDashboard/main.libsonnet, examples/runtimeDashboard/variables.libsonnet
Variables has a more intuitive API since #41
=> fix(docs): update examples

grafonnet-base/main.libsonnet
fixes #49
This regression was introduced recently, this PR fixes it.
=> fix(base): set type on row to constant

README.md, docs/README.md
Usage will likely need a great deal of love, but here's a small start to help folks who front-load all the install steps before starting a project.
=> Minor change to install doc to clarify how we work with jsonnet

Makefile, docs/grafonnet/panel/row.md, gen/grafonnet-v9.4.0/docs/grafonnet/panel/row.md, grafonnet-base/main.libsonnet, test/jsonnetfile.json, test/row_test.jsonnet
=> fix(base): set type on row to constant (for real this time)

grafonnet-base/util/panel.libsonnet, test/util_test.jsonnet
Result of today's mobsession.
- Use ~std.mapWithIndex~ std.foldl
- Provide unit test that ensures the order is maintained
- Following comments: ensure collisions do not happen (track index)
=> refactor(util): improve setPanelIDs

grafonnet-base/veneer/variable.libsonnet
=> Veneer: fix spelling

grafonnet-base/util/dashboard.libsonnet
I've made an improved version of this split function upstream, this PR uses that.
This is covered by unit tests: https://github.com/grafana/grafonnet/blob/76d498e326303645dc6e7310d14816320ae7fff3/test/util_test.jsonnet#L139-L155
=> refactor(util): replace split function with upstream xtd.splitEscape

docs.libsonnet, docs/examples/runtimeDashboard.md, docs/examples/simple.md, examples/docs/helpers.libsonnet, examples/docs/runtimeDashboard.libsonnet, examples/docs/simple.libsonnet, examples/runtimeDashboard/main.libsonnet
=> docs: improve examples

examples/redMethod/jsonnetfile.json, examples/redMethod/lib/g.libsonnet, examples/runtimeDashboard/panels.libsonnet
Testing the last few commits to main against the examples, using the examples as a smoke test.
=> docs: fix examples

grafonnet-base/veneer/variable.libsonnet
=> fix: withAutoOption

docs/API/dashboard/index.md, docs/API/dashboard/link.md, gen/grafonnet-v10.0.0/docs/grafonnet/dashboard/index.md, gen/grafonnet-v10.0.0/docs/grafonnet/dashboard/link.md, gen/grafonnet-v9.4.0/docs/grafonnet/dashboard/index.md, gen/grafonnet-v9.4.0/docs/grafonnet/dashboard/link.md, gen/grafonnet-v9.5.0/docs/grafonnet/dashboard/index.md, gen/grafonnet-v9.5.0/docs/grafonnet/dashboard/link.md, grafonnet-base/veneer/core.libsonnet, grafonnet-base/veneer/link.libsonnet
=> docs: document dashboard links with example

grafonnet-base/veneer/variable.libsonnet
=> fix(veneer): make  optional argument for label_values

Makefile, examples/redMethod/main.libsonnet, examples/redMethod/output.json, examples/runtimeDashboard/output.json, examples/simple/output.json, test/lib/g.libsonnet, test/smoke_test.jsonnet
With these smoke tests, we'll be able to catch regressions that span multiple components.
=> test: add smoke tests for examples/

custom/panel.libsonnet, custom/util/grid.libsonnet, docs/API/util.md, gen/grafonnet-v10.0.0/custom/panel.libsonnet, gen/grafonnet-v10.0.0/custom/util/grid.libsonnet, gen/grafonnet-v10.0.0/docs/grafonnet/util.md, gen/grafonnet-v9.4.0/custom/panel.libsonnet, gen/grafonnet-v9.4.0/custom/util/grid.libsonnet, gen/grafonnet-v9.4.0/docs/grafonnet/util.md, gen/grafonnet-v9.5.0/custom/panel.libsonnet, gen/grafonnet-v9.5.0/custom/util/grid.libsonnet, gen/grafonnet-v9.5.0/docs/grafonnet/util.md
=> fix: recover changes that got lost in refactor

Makefile, custom/util/grid.libsonnet
title says it, missed fmt'ing a file
=> style: fmt + make target

custom/row.libsonnet, custom/util/grid.libsonnet, custom/util/panel.libsonnet, docs/API/panel/row.md, docs/API/util.md, gen/grafonnet-v10.0.0/custom/row.libsonnet, gen/grafonnet-v10.0.0/custom/util/grid.libsonnet, gen/grafonnet-v10.0.0/custom/util/panel.libsonnet, gen/grafonnet-v10.0.0/docs/panel/row.md, gen/grafonnet-v10.0.0/docs/util.md, gen/grafonnet-v10.1.0/custom/row.libsonnet, gen/grafonnet-v10.1.0/custom/util/grid.libsonnet, gen/grafonnet-v10.1.0/custom/util/panel.libsonnet, gen/grafonnet-v10.1.0/docs/panel/row.md, gen/grafonnet-v10.1.0/docs/util.md, gen/grafonnet-v9.4.0/custom/row.libsonnet, gen/grafonnet-v9.4.0/custom/util/grid.libsonnet, gen/grafonnet-v9.4.0/custom/util/panel.libsonnet, gen/grafonnet-v9.4.0/docs/panel/row.md, gen/grafonnet-v9.4.0/docs/util.md, gen/grafonnet-v9.5.0/custom/row.libsonnet, gen/grafonnet-v9.5.0/custom/util/grid.libsonnet, gen/grafonnet-v9.5.0/custom/util/panel.libsonnet, gen/grafonnet-v9.5.0/docs/panel/row.md, gen/grafonnet-v9.5.0/docs/util.md, test/util_test.jsonnet
This PR adds a bunch of helper functions that could be used to work with rows and gridPos.
This should help resolve issues like #145
=> feat(util): provide helper functions to deal with gridPos and rows

custom/util/grid.libsonnet, gen/grafonnet-v10.0.0/custom/util/grid.libsonnet, gen/grafonnet-v10.1.0/custom/util/grid.libsonnet, gen/grafonnet-v9.4.0/custom/util/grid.libsonnet, gen/grafonnet-v9.5.0/custom/util/grid.libsonnet, test/util_test.jsonnet
Missed this, also added a unit test for it.
=> fix(util/grid): respect startY flag

custom/dashboard.libsonnet, docs/API/dashboard/index.md, gen/grafonnet-v10.0.0/custom/dashboard.libsonnet, gen/grafonnet-v10.0.0/docs/dashboard/index.md, gen/grafonnet-v10.1.0/custom/dashboard.libsonnet, gen/grafonnet-v10.1.0/docs/dashboard/index.md, gen/grafonnet-v10.2.0/custom/dashboard.libsonnet, gen/grafonnet-v10.2.0/docs/dashboard/index.md, gen/grafonnet-v10.3.0/custom/dashboard.libsonnet, gen/grafonnet-v10.3.0/docs/dashboard/index.md, gen/grafonnet-v10.4.0/custom/dashboard.libsonnet, gen/grafonnet-v10.4.0/docs/dashboard/index.md, gen/grafonnet-v9.4.0/custom/dashboard.libsonnet, gen/grafonnet-v9.4.0/docs/dashboard/index.md, gen/grafonnet-v9.5.0/custom/dashboard.libsonnet, gen/grafonnet-v9.5.0/docs/dashboard/index.md
oops, missed the documentation on this (related to #179)
=> docs: properly document new parameter

generator/jsonnetfile.json
=> chore: match main for crdsonnet

gen/grafonnet-v10.0.0/custom/dashboard/variable.libsonnet, gen/grafonnet-v10.0.0/docs/dashboard/variable.md, gen/grafonnet-v10.1.0/custom/dashboard/variable.libsonnet, gen/grafonnet-v10.1.0/docs/dashboard/variable.md, gen/grafonnet-v10.2.0/custom/dashboard/variable.libsonnet, gen/grafonnet-v10.2.0/docs/dashboard/variable.md, gen/grafonnet-v10.3.0/custom/dashboard/variable.libsonnet, gen/grafonnet-v10.3.0/docs/dashboard/variable.md, gen/grafonnet-v9.4.0/custom/dashboard/variable.libsonnet, gen/grafonnet-v9.4.0/docs/dashboard/variable.md, gen/grafonnet-v9.5.0/custom/dashboard/variable.libsonnet, gen/grafonnet-v9.5.0/docs/dashboard/variable.md
#189 only generated the latest, this covers the rest.
=> chore: generate all after #189 merge

docs/API/panel/alertList/index.md, gen/grafonnet-v11.0.0/docs/panel/alertList/index.md, gen/grafonnet-v11.0.0/panel/alertList.libsonnet, generator/patches/schemas.libsonnet
=> fix(alertList): set correct type

docs/API/query/expr/TypeClassicConditions/index.md, docs/API/query/expr/TypeMath.md, docs/API/query/expr/TypeReduce.md, docs/API/query/expr/TypeResample.md, docs/API/query/expr/TypeSql.md, docs/API/query/expr/TypeThreshold/index.md, gen/grafonnet-v11.0.0/docs/query/expr/TypeClassicConditions/index.md, gen/grafonnet-v11.0.0/docs/query/expr/TypeMath.md, gen/grafonnet-v11.0.0/docs/query/expr/TypeReduce.md, gen/grafonnet-v11.0.0/docs/query/expr/TypeResample.md, gen/grafonnet-v11.0.0/docs/query/expr/TypeSql.md, gen/grafonnet-v11.0.0/docs/query/expr/TypeThreshold/index.md, gen/grafonnet-v11.0.0/query/expr.libsonnet
=> chore: run make -B generate tracking latest foundation-sdk

gen/grafonnet-v11.0.0/custom/util/grid.libsonnet
=> fix: update util/grid in v11.0.0

catalog-info.yaml
Title says it, let's make it discoverable internally.
=> chore: add repo to backstage
